# Project tasks. Every recipe calls .venv/bin/ explicitly, so it works whether
# or not you remembered to `source .venv/bin/activate` -- and, more to the
# point, it cannot silently install into or run from your base environment.
#
#   make setup    create .venv and install pinned dependencies
#   make test     run the test suite
#   make lint     check formatting and linting
#   make format   apply formatting
#   make corpus   build data/processed/corpus.parquet
#   make lock     re-pin requirements.lock.txt after changing requirements.txt

PYTHON ?= python3
VENV   := .venv
BIN    := $(VENV)/bin
# Stamp file, so the other targets install only when the lockfile has actually
# changed -- not on every `make test`.
STAMP  := $(VENV)/.installed

.PHONY: help setup test lint format corpus smoke lock clean

help:
	@grep -E '^#   make' $(MAKEFILE_LIST) | sed 's/^#   //'

# Installs the exact pinned versions, so everyone on the team runs the same
# thing. Change dependencies in requirements.txt, then `make lock`.
$(STAMP): requirements.lock.txt
	$(PYTHON) -m venv $(VENV)
	$(BIN)/python -m pip install --quiet --upgrade pip
	$(BIN)/python -m pip install --quiet -r requirements.lock.txt
	@touch $(STAMP)

setup: $(STAMP)
	@echo "Environment ready: $$($(BIN)/python --version) in $(VENV)"
	@echo "Activate with:  source $(VENV)/bin/activate"
	@echo "Then copy .env.example to .env and fill in your API keys."

test: $(STAMP)
	$(BIN)/pytest -q

lint: $(STAMP)
	$(BIN)/ruff check code/
	$(BIN)/black --check code/

format: $(STAMP)
	$(BIN)/black code/
	$(BIN)/ruff check --fix code/

# Full corpus build. Needs congress_speeches_2001_2017.parquet in
# data/raw/stanford/ -- see docs/notes/2026-09-15_stanford_dataset.md.
corpus: $(STAMP)
	$(BIN)/python code/scripts/build_corpus.py

# Same, but reads only the first 50k rows: validates the raw schema and the
# independents roster in seconds. Run this before the full build.
smoke: $(STAMP)
	$(BIN)/python code/scripts/build_corpus.py --limit 50000

# Re-pin after editing requirements.txt. Builds a throwaway environment so the
# lock records exactly what requirements.txt resolves to, with nothing left
# over from whatever happens to be installed in .venv right now.
lock:
	rm -rf .venv-lock
	$(PYTHON) -m venv .venv-lock
	.venv-lock/bin/python -m pip install --quiet --upgrade pip
	.venv-lock/bin/python -m pip install --quiet -r requirements.txt
	@printf '# Generated by `make lock` from requirements.txt -- do not edit by hand.\n# Install with: pip install -r requirements.lock.txt\n' > requirements.lock.txt
	.venv-lock/bin/python -m pip freeze --exclude-editable >> requirements.lock.txt
	rm -rf .venv-lock
	@echo "Re-pinned requirements.lock.txt -- commit it alongside requirements.txt."

clean:
	rm -rf $(VENV) .venv-lock .pytest_cache .ruff_cache
	find code -name __pycache__ -type d -exec rm -rf {} +
